### ISSUE TITLE
Can't reproduce one of the figure of the result

### ISSUE THREAD

**Issue by damaoooo** [Cisco-Talos/binary_function_similarity#42]
Hi, 

I was trying to reproduce the figure 2 from your paper, which shows below
![image1](https://github.com/Cisco-Talos/binary_function_similarity/assets/45312642/ec85574a-3df9-48a3-b7bf-8bebe10acc3a)

Since it shows with the table of Dataset-1, so I assume it comes from Dataset-1

I downloaded the feature files and result files from `gdrive_download.py`, then use the `Results/notebooks/MRR@10 and Recall@K.ipynb` to produce the figure, but this is the figure I get

![image2](https://github.com/Cisco-Talos/binary_function_similarity/assets/45312642/d8226a67-538d-4bb9-9132-3787cc53ea6a)

It looks weird:
1. Traditional method `Catalog` surpassed all other ML based works. 
2. The labels of curve and the number of models are different

Maybe the figure comes from the Dataset-2, because I have found the XO output is quire similar, however:

1. in the downloaded dataset-2 result file and feature file, there is no `XM` Task
3. in the file `DBs/Dataset-2/Dataset-2 creation.ipynb`, cell 4, the variable `DATASET_TWO_DICT`,  there's no `XM` task, only `XA`, `XA+XO`, `XO` are provided.
4. in the file `Results/notebooks/MRR@10 and Recall@K.ipynb`, the `XM` result is also missing.

I might have made something wrong or something is missing in my steps. I am very appraciate it if you can help me to figure it out.

Thanks.

**Comment by jimmy-sonny** [comment]
Thank you @damaoooo for opening this issue.

The two plots in Figure 2 are computed from Dataset 2, although it is true that it is not clear from the description in the paper.

Left figure corresponds to the `XO` test [`Recall@K_XO_min.png`](https://github.com/Cisco-Talos/binary_function_similarity/blob/main/Results/notebooks/metrics_and_plots/Dataset-2/Recall%40K_XO_min.png), while right figure correponds to the `XA + XO` test [`Recall%40K_XA%2BXO_min.png`](https://github.com/Cisco-Talos/binary_function_similarity/blob/main/Results/notebooks/metrics_and_plots/Dataset-2/Recall%40K_XA%2BXO_min.png).

There are some minor differences in the plots and in the nomenclature. I'll investigate and update the code release if necessary.

**Comment by jimmy-sonny** [comment]
@damaoooo 

I've updated the [MRR@10 and Recall@K.ipynb](Results/notebooks/MRR@10 and Recall@K.ipynb) notebook to include the missing tests and to display the same nomenclature as in the paper.

There is a minor difference in the FunctionSimSearch (`FSS: G+M`) and Catalog1 (`Catalog1: size 128`) results compared to what has been presented in the paper because of a minor inconsistency in the ranking computation that has been fixed in this code release.

The left plot in Figure2 corresponds to [Recall@K_XO_min.png](Results/notebooks/metrics_and_plots/Dataset-2/Recall%40K_XO_min.png), while the right one corresponds to [Recall%40K_XA%2BXO_min.png](Results/notebooks/metrics_and_plots/Dataset-2/Recall%40K_XA%2BXO_min.png).

**Comment by jimmy-sonny** [comment]
Closing the issue.
